import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    ".agents/**",
    ".claude/**",
    "graphify-out/**",
    "playwright-report/**",
    "test-results/**",
    ".playwright-state/**",
    // Generated by `supabase start` (Edge Runtime bootstrap, minified). Not in
    // git, but ESLint's flat config does not read .gitignore, so without this
    // every developer who follows the local-stack workflow in README breaks
    // `npm run check`.
    "supabase/.temp/**",
  ]),
]);

export default eslintConfig;
